-- Wielded Item Rotation Overrides - [item_name]=degrees,

wield3d_rotation = {
	["default:torch"]=315,
	["default:sapling"]=315,
	["flowers:dandelion_white"]=315,
	["flowers:dandelion_yellow"]=315,
	["flowers:geranium"]=315,
	["flowers:rose"]=315,
	["flowers:tulip"]=315,
	["flowers:viola"]=315,
	["default:shovel_wood"]=270,
	["default:shovel_stone"]=270,
	["default:shovel_steel"]=270,
	["default:shovel_bronze"]=270,
	["default:shovel_mese"]=270,
	["default:shovel_diamond"]=270,
	["bucket:bucket_empty"]=270,
	["bucket:bucket_water"]=270,
	["bucket:bucket_lava"]=270,
	["screwdriver:screwdriver"]=270,
	["screwdriver:screwdriver1"]=270,
	["screwdriver:screwdriver2"]=270,
	["screwdriver:screwdriver3"]=270,
	["screwdriver:screwdriver4"]=270,
	["vessels:glass_bottle"]=270,
	["vessels:drinking_glass"]=270,
	["vessels:steel_bottle"]=270,
}

